# Generated by Django 5.1.6 on 2025-03-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
    ]
