# Generated by Django 5.1.6 on 2025-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default='2000-03-15'),
        ),
        migrations.AddField(
            model_name='account',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images/'),
        ),
    ]
