# Generated by Django 5.1.6 on 2025-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_account_gender_alter_account_personal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
