# Generated by Django 5.1.6 on 2025-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthRecords', '0004_disease_doctor_name_disease_doctor_phone_mrirecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='severity',
            field=models.CharField(max_length=20),
        ),
    ]
