# Generated by Django 5.1.6 on 2025-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='dosage',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='medications',
            name='pills_in_a_time',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='medications',
            name='time_in_a_day',
            field=models.JSONField(default='0'),
        ),
    ]
