# Generated by Django 5.1.6 on 2025-03-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medications', '0002_medications_dosage_medications_pills_in_a_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medications',
            name='time_in_a_day',
            field=models.JSONField(default=dict),
        ),
    ]
